# Intent Parser Micro-Model Config (10M params)
# Specialized for extracting user intent from natural language

base_model: microsoft/Phi-3.5-mini-instruct  # 3.8B base, we'll heavily prune
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

# Dataset pointing to approach-specific training data
datasets:
  - path: ./training_approaches/swarm_architecture/intent_parser/intent_data.jsonl
    type: completion
    
# Small model optimizations
load_in_8bit: false
load_in_4bit: true
strict: false

# LoRA for extreme efficiency
adapter: qlora
lora_r: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target_linear: true

# Training parameters for small model
gradient_accumulation_steps: 1
micro_batch_size: 2
num_epochs: 3
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0003

# Output to approach-specific folder
output_dir: ./training_approaches/swarm_architecture/intent_parser/output

# Pruning/distillation settings
model_max_length: 512  # Short context for intent parsing
