base_model: Qwen/Qwen2.5-Coder-7B

strict: false
chat_template: qwen3

datasets:
  - path: ./bcl_complete_training.jsonl
    type: alpaca

val_set_size: 0.05
output_dir: ./outputs/bcl_physics_gpu
dataset_prepared_path: last_run_prepared

sequence_len: 2048
sample_packing: false
eval_sample_packing: false
pad_to_sequence_len: false

# A4000 GPU settings with fixes
adapter: qlora
load_in_4bit: true
bnb_4bit_compute_dtype: float16  # Use fp16 for computation
bnb_4bit_use_double_quant: true  # Better compression
bnb_4bit_quant_type: nf4  # Normalized float 4-bit

lora_r: 64
lora_alpha: 128
lora_dropout: 0.05
lora_target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - down_proj
  - up_proj
  - gate_proj

wandb_project: bcl-physics-gpu
wandb_name: qwen-bcl-physics-a4000

gradient_accumulation_steps: 4
micro_batch_size: 4
num_epochs: 2
optimizer: adamw_torch_4bit
lr_scheduler: cosine
learning_rate: 0.0002

# Precision settings
bf16: false  # Disable for now
tf32: false  # Disable for now
fp16: true   # Use fp16

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false

logging_steps: 20
eval_steps: 100
save_steps: 200

warmup_ratio: 0.1
weight_decay: 0.01

# Early stopping
early_stopping_patience: 3
load_best_model_at_end: true
metric_for_best_model: eval_loss
greater_is_better: false

# IMPORTANT: Prevent meta tensor issues
torch_empty_cache_steps: 50
ddp_find_unused_parameters: false
deepspeed: