base_model: Qwen/Qwen2.5-Coder-32B
# Or use local path if you have it downloaded

plugins:
  - axolotl.integrations.cut_cross_entropy.CutCrossEntropyPlugin
strict: false

chat_template: qwen3
datasets:
  - path: ./bcl_training_data.jsonl
    type: alpaca
    format: >-
      {instruction}
      
      Input: {input}
      
      Output: {output}
val_set_size: 0.05  # 5% for validation
output_dir: ./outputs/bcl_finetune
dataset_prepared_path: last_run_prepared

sequence_len: 2048
sample_packing: false  # Better for specialized domains
eval_sample_packing: false
pad_to_sequence_len: false

load_in_4bit: true
adapter: qlora
lora_r: 32  # Increased for domain adaptation
lora_alpha: 64
lora_target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - down_proj
  - up_proj
lora_mlp_kernel: true
lora_qkv_kernel: true
lora_o_kernel: true

wandb_project: bcl-finetune
wandb_entity: 
wandb_watch:
wandb_name: qwen3-bcl-physics
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 3
optimizer: adamw_torch_4bit
lr_scheduler: cosine
learning_rate: 0.0002

bf16: auto
tf32: true

gradient_checkpointing: offload
gradient_checkpointing_kwargs:
  use_reentrant: false
resume_from_checkpoint:
logging_steps: 10
flash_attention: true

warmup_steps: 100
evals_per_epoch: 4
saves_per_epoch: 1
weight_decay: 0.01
special_tokens: