base_model: Qwen/Qwen2.5-Coder-7B
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

# Force specific device placement
device_map: null  # Disable auto device mapping
model_kwargs:
  torch_dtype: torch.float16
  trust_remote_code: true
  # Don't use device_map in model_kwargs

datasets:
  - path: ./bcl_complete_training.jsonl
    type: alpaca

output_dir: ./outputs/bcl_physics_gpu_final
val_set_size: 0.05

sequence_len: 1024
sample_packing: false
pad_to_sequence_len: false

# GPU-optimized LoRA settings
adapter: lora
lora_r: 32
lora_alpha: 64
lora_dropout: 0.05
lora_target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj

# Training settings for A4000
micro_batch_size: 4
gradient_accumulation_steps: 2
num_epochs: 2
learning_rate: 0.0002
optimizer: adamw_torch
lr_scheduler: cosine

# GPU precision settings
fp16: true
bf16: false  # Even though A4000 supports it, fp16 is more stable
tf32: false

# Memory optimization
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false

# Training schedule
logging_steps: 20
eval_steps: 100
save_steps: 200
warmup_ratio: 0.1
weight_decay: 0.01

# Early stopping
early_stopping_patience: 3
load_best_model_at_end: true
metric_for_best_model: eval_loss
greater_is_better: false

# Disable features that might cause issues
deepspeed:
xformers_attention: false
flash_attention: false
sample_packing: false
trust_remote_code: true
ddp_find_unused_parameters: false

# Chat template
chat_template: qwen3

# Explicitly set
is_llama_derived_model: false