# SmolLM-360M Orchestrator Config
# Coordinates all micro-models and handles routing

base_model: HuggingFaceTB/SmolLM-360M  # Larger variant for orchestration
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

# Dataset
datasets:
  - path: ./training_approaches/swarm_architecture/orchestrator/training_data.jsonl
    type: alpaca

# Model optimizations
load_in_8bit: false
load_in_4bit: true
strict: false

# LoRA configuration for orchestrator
adapter: qlora
lora_r: 32         # Larger rank for complex routing
lora_alpha: 64
lora_dropout: 0.05
lora_target_linear: true
lora_modules_to_save:
  - embed_tokens
  - lm_head

# Training
gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 10      # More training for complex coordination
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0003
warmup_steps: 50

# Longer context for multi-step operations
max_packed_sequence_len: 1024
pad_to_sequence_len: false

# Output
output_dir: ./training_approaches/swarm_architecture/orchestrator/output
save_strategy: steps
save_steps: 20

# Logging
logging_steps: 10
wandb_mode: disabled

# Eval
val_set_size: 0.1
early_stopping_patience: 5
