# SmolLM-135M Context Manager Config
# Maintains conversation state and entity resolution

base_model: HuggingFaceTB/SmolLM-135M
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

# Dataset
datasets:
  - path: ./training_approaches/swarm_architecture/context_manager/training_data.jsonl
    type: alpaca
    
# Small model optimizations
load_in_8bit: false
load_in_4bit: true
strict: false

# LoRA configuration
adapter: qlora
lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true

# Training
gradient_accumulation_steps: 2
micro_batch_size: 2
num_epochs: 5
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0005

# Context window for state tracking
max_packed_sequence_len: 512
pad_to_sequence_len: true

# Output
output_dir: ./training_approaches/swarm_architecture/context_manager/output
save_steps: 20

# Logging
logging_steps: 5
wandb_mode: disabled
